let
    Source = List.Dates(StartDate, #"Num of Days", #duration(1, 0, 0, 0)),
    #"Converted to Table1" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table1",{{"Column1", "Date"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    StartDate = #date(2007, 1, 1),
    Today = #date(2009, 12, 31),
    #"Num of Days" = Duration.Days(Today-StartDate)+1,
    #"FInal Table" = #"Changed Type",
    #"Inserted Year" = Table.AddColumn(#"FInal Table", "Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Quarter", "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", "Month", each Date.Month([Date]), Int64.Type),
    #"Sorted Rows" = Table.Sort(#"Inserted Month",{{"Date", Order.Ascending}})
in
    #"Sorted Rows"